"""empty message

Revision ID: 9e14b3368f37
Revises: 08020334aca6
Create Date: 2021-11-08 19:25:50.726803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e14b3368f37'
down_revision = '08020334aca6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('winner', sa.String(length=16), nullable=True),
    sa.Column('player_x_id', sa.Integer(), nullable=True),
    sa.Column('player_o_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_o_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['player_x_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    # ### end Alembic commands ###
